apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-uploads-1
  namespace: mern
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
  namespace: mern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: us.gcr.io/project-blog-310502/node-server
        imagePullPolicy: Always
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MONGO_URI  
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: SECRET  
        ports:
        - containerPort: 8080
        
    
---

apiVersion: v1
kind: Service
metadata:
  name: mi-servicio-node
  namespace: mern  
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP