version: "2.2"
services:
    builder:
        image: node-server:1.0
        build: .
        env_file:
        - .env
        volumes:
            - ./backend/:/usr/src/app
            - /usr/src/app/node_modules